package:
  name: glibc
  version: 2.39
  epoch: 6
  description: "the GNU C library"
  copyright:
    - license: LGPL-2.1-or-later
  resources:
    cpu: 16
    memory: 16Gi
  dependencies:
    runtime:
      # This prevents Alpine users from being able to `apk add` any Wolfi packages
      # that depend on glibc, if they happen to have configured both repositories.
      # Only apk-tools respects this constraint; apko-based tools don't respect
      # the ! constraint.
      - '!musl'
      - glibc-locale-posix
      - wolfi-baselayout
  scriptlets:
    trigger:
      paths:
        - /lib
        - /lib64
        - /usr/lib
        - /usr/lib64
      script: |
        #!/bin/busybox sh
        /sbin/ldconfig

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - gawk
      - grep
      - python3
      - rdfind
      - texinfo
      - wolfi-baselayout
      - zlib

pipeline:
  - uses: fetch
    with:
      uri: http://ftp.gnu.org/gnu/libc/glibc-${{package.version}}.tar.xz
      expected-sha256: f77bd47cf8170c57365ae7bf86696c118adb3b120d3259c64c502d3dc1e2d926

  - name: 'Set up build directory'
    runs: |
      mkdir build

  - name: 'Configure glibc'
    runs: |
      cd build
      echo "user-defined-trusted-dirs=/usr/local/lib:/usr/local/lib64:/usr/lib:/usr/lib64:/lib:/lib64" >> configparms.base
      echo "rtlddir=/lib" >> configparms.base
      echo "slibdir=/lib" >> configparms.base
      echo "libdir=/usr/lib" >> configparms.base

      echo "build-programs=no" > configparms
      cat configparms.base >> configparms

      # We remove fortify when building the libraries
      export CPPFLAGS=${CPPFLAGS/-Wp,-D_FORTIFY_SOURCE=3/}

      ../configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --datadir=/usr/share \
        --includedir=/usr/include \
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --disable-werror \
        --disable-crypt \
        --enable-kernel=4.9

  - runs: |
      export CPPFLAGS=${CPPFLAGS/-Wp,-D_FORTIFY_SOURCE=3/}
      make -C build -j$(nproc)

  - runs: |
      # Build the programs with fortify
      echo "build-programs=yes" > build/configparms
      echo "CPPFLAGS += -Wp,-D_FORTIFY_SOURCE=3" >> build/configparms
      cat build/configparms.base >> build/configparms
      make -C build -j$(nproc)

  - runs: |
      make -C build -j$(nproc) install DESTDIR="${{targets.destdir}}"

  - name: "Set up ldconfig"
    runs: |
      cat << EOF > "${{targets.destdir}}"/etc/ld.so.conf
      /usr/local/lib
      /usr/local/lib64
      /lib
      /lib64
      /usr/lib
      /usr/lib64
      EOF

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - name: 'Generate and install locale data'
    runs: |
      make -C build -j$(nproc) localedata/install-locale-files DESTDIR="${{targets.destdir}}"

  - uses: strip

data:
  - name: locales
    items:
      de: German
      en: English

subpackages:
  - name: "ld-linux"
    description: "the GLIBC ELF interpreter"
    pipeline:
      - assertions:
          required-steps: 1
        pipeline:
          - if: ${{build.arch}} == 'aarch64'
            runs: |
              mkdir -p "${{targets.subpkgdir}}"/lib
              mv "${{targets.destdir}}"/lib/ld-linux-aarch64.so.1 "${{targets.subpkgdir}}"/lib/
          # Regrettably, the LSB *requires* the GLIBC ELF loader to be installed in `/lib64`.
          - if: ${{build.arch}} == 'x86_64'
            runs: |
              mkdir -p "${{targets.subpkgdir}}"/lib64
              mv "${{targets.destdir}}"/lib/ld-linux-x86-64.so.2 "${{targets.subpkgdir}}"/lib64/
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc
          mv "${{targets.destdir}}"/etc/ld.so.* "${{targets.subpkgdir}}"/etc/
    dependencies:
      provider-priority: 10
      runtime:
        - wolfi-baselayout

  - name: "glibc-iconv"
    description: "GLIBC iconv tables"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/gconv "${{targets.subpkgdir}}"/usr/lib/

          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/iconvconfig "${{targets.subpkgdir}}"/usr/sbin

  - name: "glibc-locales"
    description: "GLIBC locale data"
    pipeline:
      - uses: split/locales
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/i18n "${{targets.subpkgdir}}"/usr/share/i18n

  - name: "tzutils"
    description: "Timezone utilities"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin

          mv "${{targets.destdir}}"/usr/bin/tzselect "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/zdump "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/sbin/zic "${{targets.subpkgdir}}"/usr/sbin

  - name: "posix-libc-utils"
    description: "POSIX XCU utilities included with the C library"
    dependencies:
      runtime:
        - bash
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/gencat "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/getconf "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/getent "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/iconv "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ldd "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/locale "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/pldd "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/libexec "${{targets.subpkgdir}}"/usr

  - name: "localedef"
    description: "Tool for defining GLIBC locales"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/localedef "${{targets.subpkgdir}}"/usr/bin

  - name: "sotruss"
    description: "Shared object tracing tool"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/audit
          mkdir -p "${{targets.subpkgdir}}"/usr/bin

          mv "${{targets.destdir}}"/usr/bin/sotruss "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/lib/audit/* "${{targets.subpkgdir}}"/usr/lib/audit/

  - name: "nscd"
    description: "NSS caching daemon"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/nscd "${{targets.subpkgdir}}"/usr/sbin/

  - name: "nss-db"
    description: "NSS module for database lookups"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/lib
          mkdir -p "${{targets.subpkgdir}}"/var

          mv "${{targets.destdir}}"/usr/bin/makedb "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/lib/libnss_db.so.2 "${{targets.subpkgdir}}"/lib
          mv "${{targets.destdir}}"/var/db "${{targets.subpkgdir}}"/var

  - name: "nss-hesiod"
    description: "NSS module for hesiod lookups"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/lib
          mv "${{targets.destdir}}"/lib/libnss_hesiod.so.2 "${{targets.subpkgdir}}"/lib

  - name: "pcprofiledump"
    description: "PC profiling tool"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/lib
          mv "${{targets.destdir}}"/lib/libpcprofile.so "${{targets.subpkgdir}}"/lib

          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/pcprofiledump "${{targets.subpkgdir}}"/usr/bin

  - name: "glibc-tracing"
    description: "GLIBC tracing and profiling utilities"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/mtrace "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/xtrace "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/sprof "${{targets.subpkgdir}}"/usr/bin

  - name: "sln"
    description: "Staticly-linked symbolic link tool"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/sbin
          mv "${{targets.destdir}}"/sbin/sln "${{targets.subpkgdir}}"/sbin

  - name: "glibc-locale-posix"
    description: "POSIX locale data for glibc"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/locale
          mv "${{targets.destdir}}"/usr/lib/locale/C.utf8 "${{targets.subpkgdir}}"/usr/lib/locale/

  - range: locales
    name: "glibc-locale-${{range.key}}"
    description: "${{range.value}} locale data for glibc"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/locale
          [ -d "${{targets.destdir}}"/usr/lib/locale/${{range.key}} ] \
            || mv "${{targets.destdir}}"/usr/lib/locale/${{range.key}}_* "${{targets.subpkgdir}}"/usr/lib/locale/
          [ -d "${{targets.destdir}}"/usr/lib/locale/${{range.key}} ] \
            && mv "${{targets.destdir}}"/usr/lib/locale/${{range.key}} "${{targets.subpkgdir}}"/usr/lib/locale/

          # glibc-locale-en is ~18x as big as it should be due to duplicate files.
          # rdfind replaces redundant files with hardlinks.
          rdfind -makehardlinks true "${{targets.subpkgdir}}"/usr/lib/locale/

  # Similar to https://packages.debian.org/bookworm/libc-bin
  - name: "libc-bin"
    description: "GNU C Library: Binaries"
    dependencies:
      runtime:
        - posix-libc-utils
        - tzutils
        - localedef
    checks:
      disabled:
        - empty

test:
  pipeline:
    - runs: |
        # Ensure locales are excluded from glibc
        cd /usr/lib/locale
        locales=$(ls | grep -v C.utf8 || true)

        if [[ -n "${locales}" ]]; then
          for locale in "${locales}"; do
            echo "Error: locale $locale found in main package, please add to locale list"
          done
          exit 1
        fi

update:
  enabled: true
  release-monitor:
    identifier: 5401