package:
  name: linux-kernel
  version: 6.6.29
  epoch: 1
  description: "the Linux kernel"
  copyright:
    - license: GPL-2.0-only WITH Linux-syscall-note

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - scanelf
      - flex
      - bison
      - bc
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
      expected-commit: a3463f08104612fc979c41fa54733e925205d3d7

  - runs: |
      make mrproper

  - runs: |
      make allnoconfig

  - runs: |
      make -j $(nproc --all)
      mkdir -p ${{targets.destdir}}/boot
      cp -rv arch/x86/boot/bzImage ${{targets.destdir}}/boot/bzImage
      cd ${{targets.destdir}}/boot
      ln -s ./vmlinuz ./bzImage
update:
  enabled: true
  manual: true # be careful upgrading this package
  github:
    identifier: gregkh/linux
    strip-prefix: v
    use-tag: true
    tag-filter: v6.6.