package:
  name: wolfi-base
  version: 1
  epoch: 6
  description: "Wolfi base metapackage"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash
      - coreutils

environment:
  contents:
    packages:
      - bash
      - coreutils

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"

update:
  enabled: false