package:
  name: bash
  version: 5.2.32
  epoch: 0
  description: "GNU bourne again shell"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/bash/bash-${{package.version}}.tar.gz
      expected-sha256: d3ef80d2b67d8cbbe4d3265c63a72c46f9b278ead6e0e06d61801b58f23f50b5

  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --bindir=/bin \
        --sysconfdir=/etc \
        --without-libidn \
        --with-ssl=openssl \
        --disable-nls \
        --enable-readline \
        --without-bash-malloc \
        --with-curses

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 166