package:
  name: dumb-init
  version: 1.2.5
  epoch: 3
  description: "minimal init system for Linux containers"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Yelp/dumb-init
      tag: v${{package.version}}
      expected-commit: 89c1502b9d40b5cb4a844498b14d74ba1dd559bf

  - uses: autoconf/make

  - runs: |
      install -sD -m 755 dumb-init "${{targets.destdir}}"/usr/bin/dumb-init

      # this seems to work when calling it via the kernel cmdline in qemu.. :shrug:
      echo '#!/bin/bash' > "${{targets.destdir}}"/init
      echo '/usr/bin/dumb-init --verbose bash' >> "${{targets.destdir}}"/init
      chmod +x "${{targets.destdir}}"/init

  - uses: strip

update:
  enabled: true
  github:
    identifier: Yelp/dumb-init
    strip-prefix: v
    use-tag: true