package:
  name: libite
  version: 2.6.1
  epoch: 1
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/troglobit/libite/releases/download/v2.6.1/libite-2.6.1.tar.gz
      expected-sha256: d0a73fa4c91c2fdae4afaa490167359ffc60beeeed47de9cbb67566f3f3f09e5

  - runs: |
      ./configure
      make -j5
      make install-strip
      ldconfig

  - name: Make Install
    runs: |
      DESTDIR="${{targets.destdir}}" make install