package:
  name: linux-kernel
  version: 6.6.29
  epoch: 0
  description: "the Linux kernel"
  copyright:
    - license: GPL-2.0-only WITH Linux-syscall-note

environment:
  contents:
    packages:
      - build-base
      - coreutils
      - gnutar
      - bash
      - findutils
      - busybox
      - ca-certificates-bundle
      - scanelf
      - flex
      - bison
      - bc
      - wolfi-baselayout
      - gmp-dev
      - mpc-dev
      - mpfr-dev
      - openssl
      - openssl-dev
      - libelf
      - elfutils-dev
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
      expected-commit: a3463f08104612fc979c41fa54733e925205d3d7

  - runs: |
      make mrproper

  - runs: |
      make defconfig
      make kvm_guest.config

  - runs: |
      make dir-pkg -j $(nproc --all)
      cp -rv tar-install/* ${{targets.destdir}}/
update:
  enabled: true
  manual: true # be careful upgrading this package
  github:
    identifier: gregkh/linux
    strip-prefix: v
    use-tag: true
    tag-filter: v6.6.
