package:
  name: wolfi-base
  version: 1
  epoch: 0
  description: "Wolfi base metapackage"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - busybox
      - wolfi-keys

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"

update:
  enabled: false