package:
  name: wolfi-baselayout
  version: 20230201
  epoch: 02
  description: "baselayout data for Wolfi"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - wolfi-baselayout

pipeline:
  - name: Generate /etc/os-release
    runs: |
      cat >wolfi-baselayout/vendor/etc/os-release <<EOF
      NAME=expert-computing-machine
      ID=expert-computing-machine
      ID_LIKE=wolfi
      VERSION_ID="${{package.version}}"
      HOME_URL="https://github.com/fwilhe2/expert-computing-machine"
      EOF

  - name: Install
    runs: |
      for i in bin etc etc/profile.d etc/secfixes.d home lib root var/log usr/bin usr/sbin usr/local/lib tmp var/spool/cron opt run usr/lib; do
        mkdir -p "${{targets.destdir}}"/${i}
      done

      for i in lib64 usr/lib64 usr/local/lib64; do
        ln -s lib "${{targets.destdir}}"/${i}
      done

      for i in etc/passwd etc/group etc/shadow etc/services etc/hosts etc/profile etc/shells etc/protocols etc/profile.d/locale.sh etc/nsswitch.conf etc/os-release etc/secfixes.d/wolfi; do
        install -m644 wolfi-baselayout/vendor/${i} "${{targets.destdir}}"/${i}
      done

      install -m600 wolfi-baselayout/vendor/etc/shadow "${{targets.destdir}}"/etc/shadow

      ln -s /etc/crontabs "${{targets.destdir}}"/var/spool/cron/crontabs
      ln -s /proc/mounts "${{targets.destdir}}"/etc/mtab
      ln -s /var/mail "${{targets.destdir}}"/var/spool/mail

      echo 'multi on' > "${{targets.destdir}}"/etc/host.conf

      chmod 0700 "${{targets.destdir}}"/root

      mkdir -p "${{targets.destdir}}"/var/empty
      chmod 755 "${{targets.destdir}}"/var/empty

      mkdir "${{targets.destdir}}"/sys

      touch "${{targets.destdir}}"/etc/machine-id

update:
  enabled: false
