name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        package:
          - bash
          - systemd
          - coreutils
    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: "${{ matrix.package }}.yaml"
        repository-append: "https://packages.wolfi.dev/os"
        keyring-append: "https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
        repository-path: ${{ github.workspace }}/packages/${{ matrix.package }}
    - run: find ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.package }}
        path: ${{ github.workspace }}/packages/${{ matrix.package }}
  rootfs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - run: mkdir rootfs
    # https://gist.github.com/stokito/4901a4b76834a8d1ec33f70d70785e67
    - run: find . -name '*.apk' -exec tar -xzvf {} -C rootfs --exclude=.PKGINFO --exclude=.SIGN* \;
    - run: tar cf rootfs.tar rootfs
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: rootfs
        path: rootfs.tar