name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        package:
          - bash
          - systemd
          - coreutils
          - linux-kernel
    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: "${{ matrix.package }}.yaml"
        repository-append: "https://packages.wolfi.dev/os"
        keyring-append: "https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
        repository-path: ${{ github.workspace }}/packages/${{ matrix.package }}
    - run: find ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.package }}
        path: ${{ github.workspace }}/packages/${{ matrix.package }}
  rootfs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - run: mkdir repo
    - run: find . -name '*.apk' -exec cp {} repo \;
    - run: make apk-index-temp
    - run: find . -name '*/APKINDEX.tar.gz' -exec tar xf {} \;
    - run: find . -name '*/APKINDEX' -exec cat {} >> apk-index-temp/APKINDEX \;
    - run: touch apk-index-temp/DESCRIPTION
    - run: cd apk-index-temp; tar cf APKINDEX.tar.gz APKINDEX DESCRIPTION
    - run: python3 .github/workflows/merge-apk-index.py
    - run: cp apk-index-temp/APKINDEX.tar.tz repo
    - run: |
        cd repo
        python3 -m http.server &
    - run: |
        docker pull cgr.dev/chainguard/apko
        docker run --rm -v ${PWD}:/work -w /work cgr.dev/chainguard/apko --log-level debug build-minirootfs os.yaml rootfs.tgz
        mkdir rootfs
        sudo tar xzf rootfs.tgz -C rootfs
        sudo /sbin/mkfs.ext4 -L root -d ./rootfs/ rootfs.ext4 2G
    - run: tar cf rootfs.tar rootfs
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: rootfs-tar
        path: rootfs.tar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: rootfs-raw
        path: rootfs.ext4