name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        package:
          - bash
          - systemd
          - coreutils
    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: "${{ matrix.package }}.yaml"
        repository-append: "https://packages.wolfi.dev/os"
        keyring-append: "https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
        repository-path: ${{ github.workspace }}/packages/${{ matrix.package }}
    - run: find ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.package }}
        path: ${{ github.workspace }}/packages/${{ matrix.package }}
